### ISSUE TITLE
Switching a cloudfoundry_app from python buildpack to docker image yields an error

### ISSUE THREAD

**Issue by janosbinder** [cloudfoundry-community/terraform-provider-cf#172] opened 2018-12-03 12:38 UTC
We have switched an internal application based from the python buildpack to a docker image based and we got the following error.

```
* module.fs_ocr_async.cloudfoundry_app.fs-ocr-async: cloudfoundry_app.fs-ocr-async: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.



Please include the following information in your report:



    Terraform Version: 0.11.10

    Resource ID: cloudfoundry_app.fs-ocr-async

    Mismatch reason: attribute mismatch: docker_image

    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"environment.SERVICE":*terraform.ResourceAttrDiff{Old:"mlfstaging-fs-ocr-async", New:"mlfstaging-fs-ocr-async", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "disk_quota":*terraform.ResourceAttrDiff{Old:"2048", New:"2048", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "service_binding.4.service_instance":*terraform.ResourceAttrDiff{Old:"2e883199-b9b7-4cc6-acf0-88e4d5e06880", New:"2e883199-b9b7-4cc6-acf0-88e4d5e06880", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "environment.RESULT_BACKEND":*terraform.ResourceAttrDiff{Old:"S3", New:"S3", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "buildpack":*terraform.ResourceAttrDiff{Old:"", New:"python_buildpack", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "environment.IS_SERVICE_IO_BOUND":*terraform.ResourceAttrDiff{Old:"false", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "environment.%":*terraform.ResourceAttrDiff{Old:"15", New:"15", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "service_binding.3.service_instance":*terraform.ResourceAttrDiff{Old:"b7bf199c-5048-454f-ae63-52ed641ff305", New:"b7bf199c-5048-454f-ae63-52ed641ff305", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "service_binding.1.service_instance":*terraform.ResourceAttrDiff{Old:"d681d306-ea98-4f66-8dc8-f47b2984b9d0", New:"d681d306-ea98-4f66-8dc8-f47b2984b9d0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "docker_credentials.username":*terraform.ResourceAttrDiff{Old:"mlf", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "space":*terraform.ResourceAttrDiff{Old:"90ff3bdd-4d5b-4861-b0a9-d1d0feba30e5", New:"90ff3bdd-4d5b-4861-b0a9-d1d0feba30e5", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "service_binding.2.service_instance":*terraform.ResourceAttrDiff{Old:"5e09c22d-3f83-4617-ad8a-3cf4051cf14f", New:"5e09c22d-3f83-4617-ad8a-3cf4051cf14f", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "docker_image":*terraform.ResourceAttrDiff{Old:"mlf.docker.repositories.sap.ondemand.com/com.sap.icn.lmlf/fs-ocr:1.48.2", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "service_binding.4.binding_id":*terraform.ResourceAttrDiff{Old:"70be3245-3b06-4d15-901d-87fb31a8322c", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "blue_green.#":*terraform.ResourceAttrDiff{Old:"1", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "memory":*terraform.ResourceAttrDiff{Old:"2048", New:"2048", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "service_binding.2.binding_id":*terraform.ResourceAttrDiff{Old:"e085dbd3-dc74-4201-bd1c-9415ac4f1a79", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "service_binding.#":*terraform.ResourceAttrDiff{Old:"5", New:"5", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "environment.DATA_TIME_TO_LIVE_MS":*terraform.ResourceAttrDiff{Old:"3600000", New:"3600000", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "blue_green.0.enable":*terraform.ResourceAttrDiff{Old:"true", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "environment.OBJECTSTORE":*terraform.ResourceAttrDiff{Old:"S3", New:"S3", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "command":*terraform.ResourceAttrDiff{Old:"", New:"./src/startup.sh", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "health_check_http_endpoint":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "service_binding.0.binding_id":*terraform.ResourceAttrDiff{Old:"e22ed6d6-7dea-456c-8245-08468fc507ee", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "health_check_type":*terraform.ResourceAttrDiff{Old:"port", New:"port", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "url":*terraform.ResourceAttrDiff{Old:"", New:"file://./downloads/fs-ocr-1.47.0/", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "health_check_timeout":*terraform.ResourceAttrDiff{Old:"180", New:"180", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "name":*terraform.ResourceAttrDiff{Old:"mlfstaging-fs-ocr-async", New:"mlfstaging-fs-ocr-async", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ports.#":*terraform.ResourceAttrDiff{Old:"0", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "environment.API_NAMESPACE":*terraform.ResourceAttrDiff{Old:"api", New:"api", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "enable_ssh":*terraform.ResourceAttrDiff{Old:"true", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "environment.RESOURCE":*terraform.ResourceAttrDiff{Old:"image/ocr", New:"image/ocr", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "service_binding.1.binding_id":*terraform.ResourceAttrDiff{Old:"d854fcbe-f937-4987-9fbc-989a41dc1a10", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "environment.SERVICE_PORT":*terraform.ResourceAttrDiff{Old:"8080", New:"8080", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "environment.NUM_OF_WORKERS":*terraform.ResourceAttrDiff{Old:"8", New:"8", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "environment.SUPPORT_ASYNC":*terraform.ResourceAttrDiff{Old:"true", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "environment.MLP_USE_XSUAA":*terraform.ResourceAttrDiff{Old:"true", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "environment.API_VERSION":*terraform.ResourceAttrDiff{Old:"v2", New:"v2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "docker_credentials.%":*terraform.ResourceAttrDiff{Old:"2", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "timeout":*terraform.ResourceAttrDiff{Old:"700", New:"700", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "environment.ENCRYPTION_KEY":*terraform.ResourceAttrDiff{Old:"0123456789123456", New:"0123456789123456", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "stopped":*terraform.ResourceAttrDiff{Old:"false", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "service_binding.0.service_instance":*terraform.ResourceAttrDiff{Old:"96591934-4917-46a4-8288-4041496f911d", New:"96591934-4917-46a4-8288-4041496f911d", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "environment.SERVICE_OWNER":*terraform.ResourceAttrDiff{Old:"sap", New:"sap", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "blue_green.0.shutdown_wait":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "stack":*terraform.ResourceAttrDiff{Old:"dca76a04-c0a0-4887-a7da-e2c9f659cbc7", New:"dca76a04-c0a0-4887-a7da-e2c9f659cbc7", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "instances":*terraform.ResourceAttrDiff{Old:"1", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "docker_credentials.password":*terraform.ResourceAttrDiff{Old:"sJ92Qq2F8DFIzxgk", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "environment.ENABLE_SWAGGER_UI":*terraform.ResourceAttrDiff{Old:"true", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "service_binding.3.binding_id":*terraform.ResourceAttrDiff{Old:"282eac3e-38e6-4b15-bf99-6f2807fb64d7", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}

    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"service_binding.4.binding_id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "environment.OBJECTSTORE":*terraform.ResourceAttrDiff{Old:"", New:"S3", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "timeout":*terraform.ResourceAttrDiff{Old:"", New:"700", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "service_binding.1.binding_id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "name":*terraform.ResourceAttrDiff{Old:"", New:"mlfstaging-fs-ocr-async", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ports.#":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "environment.SERVICE_PORT":*terraform.ResourceAttrDiff{Old:"", New:"8080", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "health_check_http_endpoint":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "environment.SERVICE":*terraform.ResourceAttrDiff{Old:"", New:"mlfstaging-fs-ocr-async", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "memory":*terraform.ResourceAttrDiff{Old:"", New:"2048", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "service_binding.1.service_instance":*terraform.ResourceAttrDiff{Old:"", New:"d681d306-ea98-4f66-8dc8-f47b2984b9d0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "service_binding.0.binding_id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "environment.IS_SERVICE_IO_BOUND":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "environment.SERVICE_OWNER":*terraform.ResourceAttrDiff{Old:"", New:"sap", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "environment.ENCRYPTION_KEY":*terraform.ResourceAttrDiff{Old:"", New:"0123456789123456", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "enable_ssh":*terraform.ResourceAttrDiff{Old:"", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "health_check_type":*terraform.ResourceAttrDiff{Old:"", New:"port", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "blue_green.0.enable":*terraform.ResourceAttrDiff{Old:"", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "service_binding.2.binding_id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "blue_green.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "service_binding.3.binding_id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "health_check_timeout":*terraform.ResourceAttrDiff{Old:"", New:"180", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "disk_quota":*terraform.ResourceAttrDiff{Old:"", New:"2048", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "service_binding.0.service_instance":*terraform.ResourceAttrDiff{Old:"", New:"96591934-4917-46a4-8288-4041496f911d", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "environment.API_NAMESPACE":*terraform.ResourceAttrDiff{Old:"", New:"api", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "environment.DATA_TIME_TO_LIVE_MS":*terraform.ResourceAttrDiff{Old:"", New:"3600000", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "service_binding.4.service_instance":*terraform.ResourceAttrDiff{Old:"", New:"2e883199-b9b7-4cc6-acf0-88e4d5e06880", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "environment.RESULT_BACKEND":*terraform.ResourceAttrDiff{Old:"", New:"S3", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "service_binding.#":*terraform.ResourceAttrDiff{Old:"", New:"5", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "environment.MLP_USE_XSUAA":*terraform.ResourceAttrDiff{Old:"", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "command":*terraform.ResourceAttrDiff{Old:"", New:"./src/startup.sh", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "environment.API_VERSION":*terraform.ResourceAttrDiff{Old:"", New:"v2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "buildpack":*terraform.ResourceAttrDiff{Old:"", New:"python_buildpack", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "space":*terraform.ResourceAttrDiff{Old:"", New:"90ff3bdd-4d5b-4861-b0a9-d1d0feba30e5", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "blue_green.0.shutdown_wait":*terraform.ResourceAttrDiff{Old:"", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "environment.SUPPORT_ASYNC":*terraform.ResourceAttrDiff{Old:"", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "service_binding.3.service_instance":*terraform.ResourceAttrDiff{Old:"", New:"b7bf199c-5048-454f-ae63-52ed641ff305", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "stopped":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "environment.RESOURCE":*terraform.ResourceAttrDiff{Old:"", New:"image/ocr", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "url":*terraform.ResourceAttrDiff{Old:"", New:"file://./downloads/fs-ocr-1.47.0/", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "environment.%":*terraform.ResourceAttrDiff{Old:"", New:"15", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "instances":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "environment.NUM_OF_WORKERS":*terraform.ResourceAttrDiff{Old:"", New:"8", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "stack":*terraform.ResourceAttrDiff{Old:"", New:"dca76a04-c0a0-4887-a7da-e2c9f659cbc7", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "environment.ENABLE_SWAGGER_UI":*terraform.ResourceAttrDiff{Old:"", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:true, Type:0x0}, "service_binding.2.service_instance":*terraform.ResourceAttrDiff{Old:"", New:"5e09c22d-3f83-4617-ad8a-3cf4051cf14f", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}



Also include as much context as you can about your config, state, and the steps you performed to trigger this error.
```

**Comment by jcarrothers-sap** [comment] 2018-12-03 19:45
https://github.com/hashicorp/terraform/issues/18382

Please see the last part of the issue description for ideas on how we might mitigate this issue.

**Comment by lixilin2301** [comment] 2018-12-04 15:14
As @jcarrothers-sap mentioned, the problem is caused by switching `url` to `docker_image`. 

I tried removing https://github.com/mevansam/terraform-provider-cf/blob/master/cloudfoundry/resource_cf_app.go#L290-L301. It works well, but I found another bug when switching `docker_image` to `url`, which is caused by https://github.com/mevansam/terraform-provider-cf/blob/master/cloudfoundry/resource_cf_app.go#L650. Since Terraform takes empty string as change and CF always takes the app with empty `docker_image` as a docker app and it gives an error of following, which from my view should be a problem from Terraform or CF lib.
```
cloudfoundry_app.spring-music: Modifying... (ID: 1c37534b-d51b-45fd-9172-1040e623d54b)
  docker_image: "cloudfoundry/diego-docker-app:latest" => ""
  url:          "" => "https://github.com/mevansam/terraform-provider-cf/raw/master/tests/cf-acceptance-tests/assets/java-spring/java-spring.jar"

Error: Error applying plan:

1 error(s) occurred:

* cloudfoundry_app.spring-music: 1 error(s) occurred:

* cloudfoundry_app.spring-music: error uploading application.
Server error, status code: 422, error code: 10008, message: cannot upload bits to a docker app

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```
One possibility to fix this would be adding another check to make docker_imageit a nil pointer if it is empty. https://github.com/lixilin2301/terraform-provider-cf/commit/ef09d0773a0d7a471693e940d9c42963170897ed.

**Comment by ArthurHlt** [comment] 2019-05-26 00:57
@janosbinder Could you check this with branch rework-back you can see changes in #203 ? You will need terraform 0.12

**Comment by ArthurHlt** [comment] 2019-12-08 03:42
Please check new release at https://github.com/cloudfoundry-community/terraform-provider-cf/releases/tag/v0.10.0 to see if it fix your issue.
I'm closing it for now, please re-open if you still found on issue on this.

**Closed by ArthurHlt** 2019-12-08 03:42 UTC
Labels: bug
