### ISSUE TITLE
plugin crashes while refreshing state of an app previously created

### ISSUE THREAD

**Issue by rpulijala** [cloudfoundry-community/terraform-provider-cf#156] opened 2018-10-11 15:45 UTC
I am using the new changes from master branch and was happy to find the previous issue of service binding and service creation wait time and even issue with app being pushed but not started were fixed, however once an app is pushed successfully and on a second run where terraform refreshes the app state it crashes, the plugin successfully gets a refresh state on existing spaces, services, routes, ups, but fails on a refresh on an existing app that was pushed, below trace log happens on an app that was successfully created on first execution but crashes on a refresh on a second execution

this is the code
```
resource "cloudfoundry_route" "config_service" {
	domain = "${data.cloudfoundry_domain.us-east.id}"
	space = "${cloudfoundry_space.s1.id}"
	hostname = "${var.cf_space}-config-service"
}

resource "cloudfoundry_app" "config_service" {
    name        = "config_service_web"
    space       = "${cloudfoundry_space.s1.id}"
    memory      =   "512"
    disk_quota  =   "1024"
    route       = { 
       default_route = "${cloudfoundry_route.config_service.id}"
    }
    docker_image = "${var.docker_image_url}"
    docker_credentials = {
        username = "${var.docker_reg_username}"
        password = "${var.docker_reg_password}"
    }
    service_binding = {
           service_instance = "${cloudfoundry_user_provided_service.logdrainer.id}" 
    }
    timeout         = 1800
    environment = {
        SPRING_APPLICATION_JSON = "${var.config_service_vault_params}"
        MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE = "health,info,metrics,prometheus,loggers,env"
    }
    enable_ssh = true
    stopped    = false
}
```

below is part of the trace log

```$ TF_LOG=trace terraform plan -var-file=dev.tfvars```

```
2018/10/11 15:09:38 [TRACE] [walkRefresh] Exiting eval tree: cloudfoundry_route.config_service
2018/10/11 15:09:38 [TRACE] dag/walk: walking "cloudfoundry_app.config_service"
2018/10/11 15:09:38 [TRACE] vertex 'root.cloudfoundry_app.config_service': walking
2018/10/11 15:09:38 [TRACE] vertex 'root.cloudfoundry_app.config_service': evaluating
2018/10/11 15:09:38 [TRACE] [walkRefresh] Entering eval tree: cloudfoundry_app.config_service
2018/10/11 15:09:38 [TRACE] root: eval: *terraform.EvalSequence
2018/10/11 15:09:38 [TRACE] root: eval: *terraform.EvalInterpolate
2018/10/11 15:09:38 [TRACE] root: eval: *terraform.EvalCountCheckComputed
cloudfoundry_app.config_service: Refreshing state... (ID: 574f316b-687d-48f8-a9b2-ca7789352c8d)
2018/10/11 15:09:38 [TRACE] root: eval: *terraform.EvalIf
2018/10/11 15:09:38 [TRACE] root: eval: *terraform.EvalCountFixZeroOneBoundary
2018/10/11 15:09:38 [TRACE] [walkRefresh] Exiting eval tree: cloudfoundry_app.config_service
2018/10/11 15:09:38 [TRACE] vertex 'root.cloudfoundry_app.config_service': expanding/walking dynamic subgraph
2018/10/11 15:09:38 [TRACE] Graph after step *terraform.ResourceCountTransformer:

cloudfoundry_app.config_service - *terraform.NodeRefreshableManagedResourceInstance
2018/10/11 15:09:38 [TRACE] OrphanResourceCount: Starting...
2018/10/11 15:09:38 [TRACE] OrphanResourceCount: Checking: cloudfoundry_app.config_service
2018/10/11 15:09:38 [TRACE] Graph after step *terraform.OrphanResourceCountTransformer:

cloudfoundry_app.config_service - *terraform.NodeRefreshableManagedResourceInstance
2018/10/11 15:09:38 [DEBUG] Attaching resource state to "cloudfoundry_app.config_service": &terraform.ResourceState{Type:"cloudfoundry_app", Dependencies:[]string{"cloudfoundry_route.config_service", "cloudfoundry_space.s1", "cloudfoundry_user_provided_service.phe-logdrainer"}, Primary:(*terraform.InstanceState)(0xc420328370), Deposed:[]*terraform.InstanceState{}, Provider:"provider.cloudfoundry", mu:sync.Mutex{state:0, sema:0x0}}
2018/10/11 15:09:38 [TRACE] Graph after step *terraform.AttachStateTransformer:

cloudfoundry_app.config_service - *terraform.NodeRefreshableManagedResourceInstance
2018/10/11 15:09:38 [TRACE] Graph after step *terraform.TargetsTransformer:

cloudfoundry_app.config_service - *terraform.NodeRefreshableManagedResourceInstance
2018/10/11 15:09:38 [DEBUG] ReferenceTransformer: "cloudfoundry_app.config_service" references: []
2018/10/11 15:09:38 [TRACE] Graph after step *terraform.ReferenceTransformer:

cloudfoundry_app.config_service - *terraform.NodeRefreshableManagedResourceInstance
2018/10/11 15:09:38 [TRACE] Graph after step *terraform.RootTransformer:

cloudfoundry_app.config_service - *terraform.NodeRefreshableManagedResourceInstance
2018/10/11 15:09:38 [TRACE] dag/walk: added new vertex: "cloudfoundry_app.config_service"
2018/10/11 15:09:38 [TRACE] dag/walk: walking "cloudfoundry_app.config_service"
2018/10/11 15:09:38 [TRACE] vertex 'root.cloudfoundry_app.config_service': walking
2018/10/11 15:09:38 [TRACE] vertex 'root.cloudfoundry_app.config_service': evaluating
2018/10/11 15:09:38 [TRACE] [walkRefresh] Entering eval tree: cloudfoundry_app.config_service
2018/10/11 15:09:38 [TRACE] root: eval: *terraform.EvalSequence
2018/10/11 15:09:38 [TRACE] root: eval: *terraform.EvalGetProvider
2018/10/11 15:09:38 [TRACE] root: eval: *terraform.EvalReadState
2018/10/11 15:09:38 [TRACE] root: eval: *terraform.EvalRefresh
2018-10-11T15:09:39.388Z [DEBUG] plugin.terraform-provider-cloudfoundry:
Error: Error refreshing state: 1 error(s) occurred:

* cloudfoundry_app.config_service: 1 error(s) occurred:

* cloudfoundry_app.config_service: cloudfoundry_app.config_service: unexpected EOF


panic: interface conversion: interface {} is nil, not float64
2018-10-11T15:09:39.388Z [DEBUG] plugin.terraform-provider-cloudfoundry:
2018-10-11T15:09:39.388Z [DEBUG] plugin.terraform-provider-cloudfoundry: goroutine 707 [running]:
2018-10-11T15:09:39.388Z [DEBUG] plugin.terraform-provider-cloudfoundry: github.com/terraform-providers/terraform-provider-cf/cloudfoundry/cfapi.(*RouteManager).readRouteMappings.func1(0x101df20, 0xc00014eed0, 0xc0004e0000)
2018-10-11T15:09:39.388Z [DEBUG] plugin.terraform-provider-cloudfoundry:        /go/src/github.com/terraform-providers/terraform-provider-cf/cloudfoundry/cfapi/route_manager.go:257 +0x8ec
2018-10-11T15:09:39.388Z [DEBUG] plugin.terraform-provider-cloudfoundry: github.com/terraform-providers/terraform-provider-cf/vendor/code.cloudfoundry.org/cli/cf/net.Gateway.ListPaginatedResources(0x138ad20, 0xc0000e6790, 0x12239f8, 0x0, 0x12a05f200, 0x0, 0x0, 0x0, 0x7f4532e26050, 0xc0002b0900, ...)
2018-10-11T15:09:39.389Z [DEBUG] plugin.terraform-provider-cloudfoundry:        /go/src/github.com/terraform-providers/terraform-provider-cf/vendor/code.cloudfoundry.org/cli/cf/net/gateway.go:155 +0x315
2018-10-11T15:09:39.390Z [DEBUG] plugin.terraform-provider-cloudfoundry: github.com/terraform-providers/terraform-provider-cf/cloudfoundry/cfapi.(*RouteManager).readRouteMappings(0xc000788410, 0xc0006beb10, 0x24, 0x11d3de0, 0x8, 0x0, 0x0, 0x0, 0x1e3f2c8, 0xc000406160)
2018-10-11T15:09:39.391Z [DEBUG] plugin.terraform-provider-cloudfoundry:        /go/src/github.com/terraform-providers/terraform-provider-cf/cloudfoundry/cfapi/route_manager.go:243 +0x258
2018-10-11T15:09:39.391Z [DEBUG] plugin.terraform-provider-cloudfoundry: github.com/terraform-providers/terraform-provider-cf/cloudfoundry/cfapi.(*RouteManager).ReadRouteMappingsByApp(0xc000788410, 0xc0006beb10, 0x24, 0x16, 0xc0006beb70, 0x24, 0xc0005e68e0, 0xc00052b988)
2018-10-11T15:09:39.391Z [DEBUG] plugin.terraform-provider-cloudfoundry:        /go/src/github.com/terraform-providers/terraform-provider-cf/cloudfoundry/cfapi/route_manager.go:235 +0x58
2018-10-11T15:09:39.391Z [DEBUG] plugin.terraform-provider-cloudfoundry: github.com/terraform-providers/terraform-provider-cf/cloudfoundry.resourceAppRead(0xc00072a150, 0x117ed20, 0xc0001b6c80, 0xc00072a150, 0x0)
2018-10-11T15:09:39.391Z [DEBUG] plugin.terraform-provider-cloudfoundry:        /go/src/github.com/terraform-providers/terraform-provider-cf/cloudfoundry/resource_cf_app.go:568 +0x2c3
2018-10-11T15:09:39.391Z [DEBUG] plugin.terraform-provider-cloudfoundry: github.com/terraform-providers/terraform-provider-cf/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc0002912d0, 0xc000184140, 0x117ed20, 0xc0001b6c80, 0xc000143218, 0x4c2701, 0xf8d4c0)
2018-10-11T15:09:39.391Z [DEBUG] plugin.terraform-provider-cloudfoundry:        /go/src/github.com/terraform-providers/terraform-provider-cf/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:354 +0x160
2018-10-11T15:09:39.392Z [DEBUG] plugin.terraform-provider-cloudfoundry: github.com/terraform-providers/terraform-provider-cf/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc000291340, 0xc0001840a0, 0xc000184140, 0xc000057500, 0x53380d134d2c6dfc, 0x7f4532ee8d80)
2018-10-11T15:09:39.393Z [DEBUG] plugin.terraform-provider-cloudfoundry:        /go/src/github.com/terraform-providers/terraform-provider-cf/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x92
2018-10-11T15:09:39.393Z [DEBUG] plugin.terraform-provider-cloudfoundry: github.com/terraform-providers/terraform-provider-cf/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc0002a1060, 0xc000406070, 0xc000406140, 0x0, 0x0)
2018-10-11T15:09:39.393Z [DEBUG] plugin.terraform-provider-cloudfoundry:        /go/src/github.com/terraform-providers/terraform-provider-cf/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
2018-10-11T15:09:39.393Z [DEBUG] plugin.terraform-provider-cloudfoundry: reflect.Value.call(0xc000385620, 0xc0001735b8, 0x13, 0x11cf283, 0x4, 0xc000538f18, 0x3, 0x3, 0xc000156d00, 0xc0002ddd08, ...)
2018-10-11T15:09:39.393Z [DEBUG] plugin.terraform-provider-cloudfoundry:        /usr/local/go/src/reflect/value.go:447 +0x449
2018-10-11T15:09:39.395Z [DEBUG] plugin.terraform-provider-cloudfoundry: reflect.Value.Call(0xc000385620, 0xc0001735b8, 0x13, 0xc000486f18, 0x3, 0x3, 0x1, 0x6607fe, 0xc000035f01)
2018-10-11T15:09:39.395Z [DEBUG] plugin.terraform-provider-cloudfoundry:        /usr/local/go/src/reflect/value.go:308 +0xa4
2018-10-11T15:09:39.395Z [DEBUG] plugin.terraform-provider-cloudfoundry: net/rpc.(*service).call(0xc0002e5840, 0xc00001b400, 0xc0000b7b30, 0xc0000b7b40, 0xc00048e580, 0xc0006409e0, 0xf8d480, 0xc000406070, 0x16, 0xf8d4c0, ...)
2018-10-11T15:09:39.395Z [DEBUG] plugin.terraform-provider-cloudfoundry:        /usr/local/go/src/net/rpc/server.go:384 +0x14e
2018-10-11T15:09:39.395Z [DEBUG] plugin.terraform-provider-cloudfoundry: created by net/rpc.(*Server).ServeCodec
2018-10-11T15:09:39.395Z [DEBUG] plugin.terraform-provider-cloudfoundry:        /usr/local/go/src/net/rpc/server.go:481 +0x47e
2018/10/11 15:09:39 [ERROR] root: eval: *terraform.EvalRefresh, err: cloudfoundry_app.config_service: unexpected EOF
2018/10/11 15:09:39 [ERROR] root: eval: *terraform.EvalSequence, err: cloudfoundry_app.config_service: unexpected EOF
2018/10/11 15:09:39 [TRACE] [walkRefresh] Exiting eval tree: cloudfoundry_app.config_service
2018/10/11 15:09:39 [TRACE] dag/walk: upstream errored, not walking "provider.cloudfoundry (close)"
2018/10/11 15:09:39 [TRACE] dag/walk: upstream errored, not walking "root"
2018/10/11 15:09:39 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-10-11T15:09:39.418Z [WARN ] plugin: error closing client during Kill: err="connection is shut down"
2018-10-11T15:09:39.427Z [DEBUG] plugin.terraform-provider-hsdp: 2018/10/11 15:09:39 [ERR] plugin: plugin server: accept unix /tmp/plugin903295768: use of closed network connection
2018-10-11T15:09:39.434Z [DEBUG] plugin: plugin process exited: path=/tffiles/terraform.d/plugins/linux_amd64/terraform-provider-cloudfoundry
2018-10-11T15:09:39.439Z [DEBUG] plugin: plugin process exited: path=/tffiles/terraform.d/plugins/linux_amd64/terraform-provider-hsdp
panic: interface conversion: interface {} is nil, not float64
2018-10-11T15:09:39.388Z [DEBUG] plugin.terraform-provider-cloudfoundry:
2018-10-11T15:09:39.388Z [DEBUG] plugin.terraform-provider-cloudfoundry: goroutine 707 [running]:
2018-10-11T15:09:39.388Z [DEBUG] plugin.terraform-provider-cloudfoundry: github.com/terraform-providers/terraform-provider-cf/cloudfoundry/cfapi.(*RouteManager).readRouteMappings.func1(0x101df20, 0xc00014eed0, 0xc0004e0000)
2018-10-11T15:09:39.388Z [DEBUG] plugin.terraform-provider-cloudfoundry:        /go/src/github.com/terraform-providers/terraform-provider-cf/cloudfoundry/cfapi/route_manager.go:257 +0x8ec
2018-10-11T15:09:39.388Z [DEBUG] plugin.terraform-provider-cloudfoundry: github.com/terraform-providers/terraform-provider-cf/vendor/code.cloudfoundry.org/cli/cf/net.Gateway.ListPaginatedResources(0x138ad20, 0xc0000e6790, 0x12239f8, 0x0, 0x12a05f200, 0x0, 0x0, 0x0, 0x7f4532e26050, 0xc0002b0900, ...)
2018-10-11T15:09:39.389Z [DEBUG] plugin.terraform-provider-cloudfoundry:        /go/src/github.com/terraform-providers/terraform-provider-cf/vendor/code.cloudfoundry.org/cli/cf/net/gateway.go:155 +0x315
2018-10-11T15:09:39.390Z [DEBUG] plugin.terraform-provider-cloudfoundry: github.com/terraform-providers/terraform-provider-cf/cloudfoundry/cfapi.(*RouteManager).readRouteMappings(0xc000788410, 0xc0006beb10, 0x24, 0x11d3de0, 0x8, 0x0, 0x0, 0x0, 0x1e3f2c8, 0xc000406160)
2018-10-11T15:09:39.391Z [DEBUG] plugin.terraform-provider-cloudfoundry:        /go/src/github.com/terraform-providers/terraform-provider-cf/cloudfoundry/cfapi/route_manager.go:243 +0x258
2018-10-11T15:09:39.391Z [DEBUG] plugin.terraform-provider-cloudfoundry: github.com/terraform-providers/terraform-provider-cf/cloudfoundry/cfapi.(*RouteManager).ReadRouteMappingsByApp(0xc000788410, 0xc0006beb10, 0x24, 0x16, 0xc0006beb70, 0x24, 0xc0005e68e0, 0xc00052b988)
2018-10-11T15:09:39.391Z [DEBUG] plugin.terraform-provider-cloudfoundry:        /go/src/github.com/terraform-providers/terraform-provider-cf/cloudfoundry/cfapi/route_manager.go:235 +0x58
2018-10-11T15:09:39.391Z [DEBUG] plugin.terraform-provider-cloudfoundry: github.com/terraform-providers/terraform-provider-cf/cloudfoundry.resourceAppRead(0xc00072a150, 0x117ed20, 0xc0001b6c80, 0xc00072a150, 0x0)
2018-10-11T15:09:39.391Z [DEBUG] plugin.terraform-provider-cloudfoundry:        /go/src/github.com/terraform-providers/terraform-provider-cf/cloudfoundry/resource_cf_app.go:568 +0x2c3
2018-10-11T15:09:39.391Z [DEBUG] plugin.terraform-provider-cloudfoundry: github.com/terraform-providers/terraform-provider-cf/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc0002912d0, 0xc000184140, 0x117ed20, 0xc0001b6c80, 0xc000143218, 0x4c2701, 0xf8d4c0)
2018-10-11T15:09:39.391Z [DEBUG] plugin.terraform-provider-cloudfoundry:        /go/src/github.com/terraform-providers/terraform-provider-cf/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:354 +0x160
2018-10-11T15:09:39.392Z [DEBUG] plugin.terraform-provider-cloudfoundry: github.com/terraform-providers/terraform-provider-cf/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc000291340, 0xc0001840a0, 0xc000184140, 0xc000057500, 0x53380d134d2c6dfc, 0x7f4532ee8d80)
2018-10-11T15:09:39.393Z [DEBUG] plugin.terraform-provider-cloudfoundry:        /go/src/github.com/terraform-providers/terraform-provider-cf/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x92
2018-10-11T15:09:39.393Z [DEBUG] plugin.terraform-provider-cloudfoundry: github.com/terraform-providers/terraform-provider-cf/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc0002a1060, 0xc000406070, 0xc000406140, 0x0, 0x0)
2018-10-11T15:09:39.393Z [DEBUG] plugin.terraform-provider-cloudfoundry:        /go/src/github.com/terraform-providers/terraform-provider-cf/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
2018-10-11T15:09:39.393Z [DEBUG] plugin.terraform-provider-cloudfoundry: reflect.Value.call(0xc000385620, 0xc0001735b8, 0x13, 0x11cf283, 0x4, 0xc000538f18, 0x3, 0x3, 0xc000156d00, 0xc0002ddd08, ...)
2018-10-11T15:09:39.393Z [DEBUG] plugin.terraform-provider-cloudfoundry:        /usr/local/go/src/reflect/value.go:447 +0x449
2018-10-11T15:09:39.395Z [DEBUG] plugin.terraform-provider-cloudfoundry: reflect.Value.Call(0xc000385620, 0xc0001735b8, 0x13, 0xc000486f18, 0x3, 0x3, 0x1, 0x6607fe, 0xc000035f01)
2018-10-11T15:09:39.395Z [DEBUG] plugin.terraform-provider-cloudfoundry:        /usr/local/go/src/reflect/value.go:308 +0xa4
2018-10-11T15:09:39.395Z [DEBUG] plugin.terraform-provider-cloudfoundry: net/rpc.(*service).call(0xc0002e5840, 0xc00001b400, 0xc0000b7b30, 0xc0000b7b40, 0xc00048e580, 0xc0006409e0, 0xf8d480, 0xc000406070, 0x16, 0xf8d4c0, ...)
2018-10-11T15:09:39.395Z [DEBUG] plugin.terraform-provider-cloudfoundry:        /usr/local/go/src/net/rpc/server.go:384 +0x14e
2018-10-11T15:09:39.395Z [DEBUG] plugin.terraform-provider-cloudfoundry: created by net/rpc.(*Server).ServeCodec
2018-10-11T15:09:39.395Z [DEBUG] plugin.terraform-provider-cloudfoundry:        /usr/local/go/src/net/rpc/server.go:481 +0x47e
2018/10/11 15:09:39 [ERROR] root: eval: *terraform.EvalRefresh, err: cloudfoundry_app.config_service: unexpected EOF
2018/10/11 15:09:39 [ERROR] root: eval: *terraform.EvalSequence, err: cloudfoundry_app.config_service: unexpected EOF
2018/10/11 15:09:39 [TRACE] [walkRefresh] Exiting eval tree: cloudfoundry_app.config_service
2018/10/11 15:09:39 [TRACE] dag/walk: upstream errored, not walking "provider.cloudfoundry (close)"
2018/10/11 15:09:39 [TRACE] dag/walk: upstream errored, not walking "root"
2018/10/11 15:09:39 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-10-11T15:09:39.418Z [WARN ] plugin: error closing client during Kill: err="connection is shut down"
2018-10-11T15:09:39.427Z [DEBUG] plugin.terraform-provider-hsdp: 2018/10/11 15:09:39 [ERR] plugin: plugin server: accept unix /tmp/plugin903295768: use of closed network connection
2018-10-11T15:09:39.434Z [DEBUG] plugin: plugin process exited: path=/tffiles/terraform.d/plugins/linux_amd64/terraform-provider-cloudfoundry
2018-10-11T15:09:39.439Z [DEBUG] plugin: plugin process exited: path=/tffiles/terraform.d/plugins/linux_amd64/terraform-provider-hsdp



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by rpulijala** [comment] 2018-10-11 18:45
@gberche-orange  let me know if you need more info to look into it

**Comment by gberche-orange** [comment] 2018-10-12 07:28
thanks @rpulijala for reporting this issue !

@jcarrothers-sap seems related to the route refresh introduced in #137, can you please have a look  ?

**Comment by jcarrothers-sap** [comment] 2018-11-16 00:03
@gberche-orange I don't think this is related to the route refresh changes from #137 as the code that is throwing this error has not changed recently.  I'm not entirely certain how this is possible short of CF giving back bad data as the stack trace indicates that the `app_port` field was not populated in the response from CF even though the API documentation indicates that it should be.

@rpulijala Is there a chance that the app had another route, not controlled by terraform, mapped to it prior to the update failure?  I suppose it is possible that there is another mapping API that could cause this field to come back as a null value.

**Comment by gberche-orange** [comment] 2018-11-16 16:43
@jcarrothers-sap Even though the CC API V2 [documentation for GET /v2/route_mappings](https://apidocs.cloudfoundry.org/6.2.0/routes_mapping/list_all_route_mappings.html) is imprecise, as the sample response displays a non null `app_port`, I understand the app_port is only supported for TCP routes and not HTTP routes. See Cf manifest examples of route syntax at https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#routes 

`yml
 routes:
  - route: example.com
  - route: www.example.com/foo
  - route: tcp-example.com:1234
`
Cloudcontroller indeed actually ignores app_ports for http routes, see https://github.com/cloudfoundry/cloud_controller_ng/blob/ea0bf3387a069395377a9df0ef04cd29a482eb9b/app/controllers/runtime/route_mappings_controller.rb#L39-L41

Do you see any possibility that the provider is now failing to parse response from the `/v2/route_mappings` endpoint with a null `app_port` whereas it was not calling this endpoint prior to #137 ?

@rpulijala Can you please help reproduce the issue? I'm unable to reproduce it with https://github.com/gberche-orange/terraform-cloudfoundry-demo/blob/6adc711ba9de5277db75c60ff9909ec295b76629/provider_cloudfoundry.tf#L51-L70 in version 0.9.9

**Comment by jcarrothers-sap** [comment] 2018-11-16 19:29
I wonder if this has something to do with the fact that the provider is using CF API that is currently marked as experimental? (https://apidocs.cloudfoundry.org/6.2.0/#route-mappings--experimental-)

> Note: The API docs are not very good about distinguishing between the route's port (for TCP routes) and the app_port feature which I suspect was added later (probably as part of Diego).  This problem specifically relates to the app_port feature which refers to which listening port of the app's container the route is bound to and not the the port the route listens on at the CF router.

The concept of an `app_port` doesn't seem to exist outside of this part of the API and thus may not be correctly populated when creating route mappings with the normal (ie. non-experimental) portions of the API.  While I haven't had a chance to experiment with all of the variables here, my current theory runs like this:
- the concept of the `app_port` is relatively new, but exists for both the HTTP and TCP route types
- the non-experimental API for mapping routes does not use the concept of an `app_port` and instead always binds the route to the first port defined for an application, even if the application has been configured to listen on multiple ports
  - this also means that this API does fails to store the `app_port` field, so that if you attempt to retrieve the details of a mapping using the experimental [Retrieve a Particular Route Mapping](https://apidocs.cloudfoundry.org/6.2.0/routes_mapping/retrieve_a_particular_route_mapping.html)
  - this is what results in a null value in the `app_port` field

Assuming this theory pans out, the question we need to address is should we:
- refactor our code to avoid the experimental API
or
- attempt to handle the case where a route is mapped to a Terraform managed app with the old API
  - this is what #159 is currently attempting to do

**Comment by gberche-orange** [comment] 2018-11-19 18:15
Discussion during weekly team meeting with @jcarrothers-sap 
* check with [CAPI team on slack](https://cloudfoundry.slack.com/messages/C07C04W4Q) that the route mapping port in the experimental [POST /v2/route_mappings](https://apidocs.cloudfoundry.org/6.2.0/routes_mapping/mapping_an_app_and_a_route.html) resource is indeed not used for https routes, and only meaningful along with TCP routes where a port was specified in the [POST /v2/routes/](https://apidocs.cloudfoundry.org/6.2.0/routes/creating_a_route.html) endpoint

**Comment by gberche-orange** [comment] 2019-05-06 16:38
Fixed by https://github.com/mevansam/terraform-provider-cf/commit/9c9d8b58989f81f3abeb38a4bac6fa56d067c5fc Issue will be closed automatically in next release when `dev` branch will be merged in `master`

**Comment by ScottGuymer** [comment] 2019-08-03 09:52
Im hitting on this issue while trying to use the provider. 

Did you find a workaround for this to be able to use the provider?

**Comment by sleungcy** [comment] 2019-11-28 00:22
I am hitting on this issue as well, does that mean 0.9.9 is unusable?

**Comment by ScottGuymer** [comment] 2019-11-28 14:26
I have had to fall back to using a manifest to deploy the apps in conjunction with this provider.

If it helps i can post some code as an example

**Closed** 2019-12-08 02:21 UTC
Labels: bug
