### ISSUE TITLE
Lifecycle error when updating stopped flag in a docker app 

### ISSUE THREAD

**Issue by lixilin2301** [cloudfoundry-community/terraform-provider-cf#183] opened 2019-01-02 15:14 UTC
The error occurs when updating `stopped` flag from `false` to `true` to start a docker app. 
```
Terraform will perform the following actions:

  ~ cloudfoundry_app.hello-push
      stopped: "false" => "true"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudfoundry_app.hello-push: Modifying... (ID: 5f8ed371-0ff3-454d-b5ad-c6296621cd81)
  stopped: "false" => "true"

Error: Error applying plan:

1 error(s) occurred:

* cloudfoundry_app.hello-push: 1 error(s) occurred:

* cloudfoundry_app.hello-push: Server error, status code: 400, error code: 100001, message: The app is invalid: Lifecycle type cannot be changed
```

In code, we don't check the app type before starting the app: https://github.com/mevansam/terraform-provider-cf/blob/master/cloudfoundry/resource_cf_app.go#L834. Instead, we should do the same as https://github.com/mevansam/terraform-provider-cf/blob/master/cloudfoundry/resource_cf_app.go#L513

If this is the case, I will work on this and prepare a PR.

**Comment by sleungcy** [comment] 2019-11-29 17:23
I am running into this issue and i tried your suggestions, but I still run into this bug

**Comment by janosbinder** [comment] 2019-11-29 17:26
Probably we have not backported that feature from our fork.

**Comment by sleungcy** [comment] 2019-11-29 18:29
This happens when upgrading docker images as well

**Comment by sleungcy** [comment] 2019-11-29 18:32
Any idea what "Lifecycle type cannot be changed" means?

**Comment by sleungcy** [comment] 2019-11-29 18:43
I think the problem is because the docker app isn't stopped during the update, so a StopDockerApp should be implemented in app_manager.go as well

**Comment by ArthurHlt** [comment] 2019-12-08 03:40
Please check new release at https://github.com/cloudfoundry-community/terraform-provider-cf/releases/tag/v0.10.0 to see if it fix your issue.
I'm closing it for now, please re-open if you still found on issue on this.

**Closed by ArthurHlt** 2019-12-08 03:40 UTC
Labels: bug
